// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/grpc.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hello struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hello) Reset()         { *m = Hello{} }
func (m *Hello) String() string { return proto.CompactTextString(m) }
func (*Hello) ProtoMessage()    {}
func (*Hello) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a1781a552648e3f4, []int{0}
}
func (m *Hello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hello.Unmarshal(m, b)
}
func (m *Hello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hello.Marshal(b, m, deterministic)
}
func (dst *Hello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hello.Merge(dst, src)
}
func (m *Hello) XXX_Size() int {
	return xxx_messageInfo_Hello.Size(m)
}
func (m *Hello) XXX_DiscardUnknown() {
	xxx_messageInfo_Hello.DiscardUnknown(m)
}

var xxx_messageInfo_Hello proto.InternalMessageInfo

func (m *Hello) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type UserInfo struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=FullName,proto3" json:"FullName,omitempty"`
	MSIDN                string   `protobuf:"bytes,4,opt,name=MSIDN,proto3" json:"MSIDN,omitempty"`
	CreateTime           string   `protobuf:"bytes,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_grpc_a1781a552648e3f4, []int{1}
}
func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (dst *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(dst, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserInfo) GetMSIDN() string {
	if m != nil {
		return m.MSIDN
	}
	return ""
}

func (m *UserInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func init() {
	proto.RegisterType((*Hello)(nil), "user.Hello")
	proto.RegisterType((*UserInfo)(nil), "user.UserInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	Ping(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Hello, error)
	SelectUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*UserInfo, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Ping(ctx context.Context, in *Hello, opts ...grpc.CallOption) (*Hello, error) {
	out := new(Hello)
	err := c.cc.Invoke(ctx, "/user.Greeter/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SelectUserInfo(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*UserInfo, error) {
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, "/user.Greeter/SelectUserInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	Ping(context.Context, *Hello) (*Hello, error)
	SelectUserInfo(context.Context, *UserInfo) (*UserInfo, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Greeter/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Ping(ctx, req.(*Hello))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SelectUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SelectUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Greeter/SelectUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SelectUserInfo(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Greeter_Ping_Handler,
		},
		{
			MethodName: "SelectUserInfo",
			Handler:    _Greeter_SelectUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/grpc.proto",
}

func init() { proto.RegisterFile("grpc/grpc.proto", fileDescriptor_grpc_a1781a552648e3f4) }

var fileDescriptor_grpc_a1781a552648e3f4 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0xda, 0xea, 0x3c, 0x83, 0x09, 0x07, 0x2f, 0x42, 0x11, 0x91, 0x78, 0xe3, 0xcd,
	0x22, 0xcc, 0x37, 0x98, 0xf5, 0x4f, 0x2f, 0x1c, 0xc3, 0xe9, 0x03, 0xc4, 0x71, 0x2c, 0x81, 0xb4,
	0x29, 0x69, 0x06, 0x5e, 0xfb, 0xe4, 0x92, 0xc4, 0x6a, 0xd9, 0x4d, 0xc2, 0xef, 0x3b, 0x7f, 0x38,
	0xdf, 0x07, 0x67, 0xb5, 0xed, 0x76, 0xb7, 0xfe, 0x11, 0x9d, 0x35, 0xce, 0x60, 0xb6, 0xef, 0xc9,
	0xf2, 0x6b, 0xc8, 0x9f, 0x49, 0x6b, 0x83, 0x05, 0x4c, 0x6b, 0x4b, 0xe4, 0x54, 0x5b, 0xb3, 0xe4,
	0x2a, 0xb9, 0x39, 0x7d, 0xfd, 0x63, 0xfe, 0x9d, 0xc0, 0xf4, 0xbd, 0x27, 0x5b, 0xb5, 0x9f, 0x06,
	0xe7, 0x90, 0x56, 0xe5, 0x6f, 0x4b, 0x5a, 0x95, 0x78, 0x0e, 0xf9, 0x43, 0x23, 0x95, 0x66, 0x69,
	0x90, 0x22, 0xf8, 0x75, 0x8f, 0x7b, 0xad, 0xd7, 0xb2, 0x21, 0x76, 0x14, 0xd7, 0x0d, 0xec, 0x27,
	0x5e, 0xb6, 0x55, 0xb9, 0x66, 0x59, 0x9c, 0x08, 0x80, 0x97, 0x00, 0xf7, 0x96, 0xa4, 0xa3, 0x37,
	0xd5, 0x10, 0xcb, 0x43, 0x69, 0xa4, 0x2c, 0x25, 0x9c, 0x3c, 0xf9, 0x83, 0xc8, 0x22, 0x87, 0x6c,
	0xa3, 0xda, 0x1a, 0x67, 0xc2, 0x7b, 0x10, 0xc1, 0x40, 0x31, 0x06, 0x3e, 0xc1, 0x25, 0xcc, 0xb7,
	0xa4, 0x69, 0xe7, 0xfe, 0x0f, 0x8f, 0x0d, 0x03, 0x17, 0x07, 0xcc, 0x27, 0xab, 0x05, 0x5c, 0x28,
	0x23, 0x42, 0x46, 0xf4, 0x25, 0x9b, 0x4e, 0x53, 0x2f, 0x7a, 0xe5, 0xff, 0x85, 0x17, 0x57, 0xb3,
	0x11, 0x6c, 0x92, 0x8f, 0xe3, 0x10, 0xe4, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xa3,
	0x60, 0x4a, 0x5b, 0x01, 0x00, 0x00,
}
